### ISSUE TITLE
Russian translation for "More Berries"

### ISSUE THREAD

**Issue by Opexpy** [MarcusElg/More-Berries#12]
I added it to the zip archive for convenience, I will update to the next version of course if there will be changes to the mod
[ru_ru.zip](https://github.com/MarcusElg/More-Berries/files/8456976/ru_ru.zip)

**Comment by Opexpy** [comment]
There were bugs at first, but all fixed and made to work on all versions of the mod. So I accidentally also added as a problem  :/

**Comment by MarcusElg** [comment]
Added to V.1.4.8

**Comment by Opexpy** [comment]
thanks, I have almost finished the new version of the translation, it will be released in the evening, because I am at college until 14:30

**Comment by Opexpy** [comment]
translation ready please! add to all versions of the mod as a mini updat
[ru v2.zip](https://github.com/MarcusElg/More-Berries/files/8489551/ru.v2.zip)
e
