### ISSUE TITLE
[SUGGESTION] Add dehydration support

### ISSUE THREAD

**Issue by Sunconure11** [MarcusElg/More-Berries#13]
Just what it says on the tin. This can be done via tags

**Comment by MarcusElg** [comment]
Which tags?

**Comment by Sunconure11** [comment]
https://github.com/Globox1997/Dehydration/tree/1.18/src/main/resources/data/dehydration/tags/items

**Comment by MarcusElg** [comment]
Ok will do

**Comment by MarcusElg** [comment]
Added in 1.4.9
