### ISSUE TITLE
Path finding

### ISSUE THREAD

**Issue by VoidLock92** [MarcusElg/More-Berries#7]
Things do not seem to path find around the new bushes. The vanilla bush works just fine and creatures will path find around them but the new ones things just constantly kill themselves on.

**Comment by MarcusElg** [comment]
I will look into it. Thanks for reporting

**Comment by MarcusElg** [comment]
Fixed in 1.4.6

**Comment by VoidLock92** [comment]
Glad to help! Thanks for fixing it :)
