### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by Sunconure11** [MarcusElg/More-Berries#8]
https://pastebin.com/xR9tYWhU

**Comment by MarcusElg** [comment]
Please test without the other mods and see if the error still occurs.

**Comment by Sunconure11** [comment]
Testing a hunch regarding this ATM

**Comment by MarcusElg** [comment]
The latest version is for 1.18.2 as displayed in the name. The issue is that there isn't a 1.18.2 version to select yet on curseforge and you always need to select a version. I'll change it to a beta version for now to hopefully avoid confusion

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/jQH72fqKQA probably the same error?
